sudo: required

services:
  - docker

before_install:
  - make docker
  - make deps
  - make db

script:
  - make tests
  -	ls -l storage
  -	ls -l storage/logs
  -	cat storage/logs/laravel.log
  -	docker-compose logs app

branches:
  only:
    - /^laravel-.*$/
