version: '2'

services:
  app:
    image: oauth2-server-laravel
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    depends_on:
      - mysql

  nodejs:
    image: node:alpine
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=oauth2_laravel
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
